### ISSUE TITLE
Portals not working - Console error below

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [poggit-orphanage/MagicTelePortal#2]
12.06 13:00:54 [Server] Server thread/DEBUG #12 /jar/pocketmine/pmmp/1.4.0-alpha12/PocketMine-MP.phar(9): include(string phar:///jar/pocketmine/pmmp/1.4.0-alpha12/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
12.06 13:00:54 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(304): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
12.06 13:00:54 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1712): pocketmine\Server->start()
12.06 13:00:54 [Server] Server thread/DEBUG #9 src/pocketmine/Server(2129): pocketmine\Server->tickProcessor()
12.06 13:00:54 [Server] Server thread/DEBUG #8 src/pocketmine/Server(2255): pocketmine\Server->tick()
12.06 13:00:54 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2507): pocketmine\Server->checkTickUpdates(integer 3112, double 1528830054.0839)
12.06 13:00:54 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2356): pocketmine\level\Level->doTick(integer 3112)
12.06 13:00:54 [Server] Server thread/DEBUG #5 src/pocketmine/level/Level(751): pocketmine\Player->onUpdate(integer 3112)
12.06 13:00:54 [Server] Server thread/DEBUG #4 src/pocketmine/Player(1702): pocketmine\Player->processMovement(integer 1)
12.06 13:00:54 [Server] Server thread/DEBUG #3 src/pocketmine/Player(1595): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:54 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(701): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:54 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(aliuly\mtp\Main object, pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:54 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): aliuly\mtp\Main->onMove(pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:54 [Server] Server thread/CRITICAL Error: "Call to undefined method aliuly\mtp\Main::getScheduler()" (EXCEPTION) in "MagicTelePortal_dev-11.phar/src/aliuly/mtp/Main" at line 245
12.06 13:00:54 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'MagicTelePortal v1.3.2-6': Call to undefined method aliuly\mtp\Main::getScheduler() on aliuly\mtp\Main
12.06 13:00:53 [Server] Server thread/DEBUG #12 /jar/pocketmine/pmmp/1.4.0-alpha12/PocketMine-MP.phar(9): include(string phar:///jar/pocketmine/pmmp/1.4.0-alpha12/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
12.06 13:00:53 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(304): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
12.06 13:00:53 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1712): pocketmine\Server->start()
12.06 13:00:53 [Server] Server thread/DEBUG #9 src/pocketmine/Server(2129): pocketmine\Server->tickProcessor()
12.06 13:00:53 [Server] Server thread/DEBUG #8 src/pocketmine/Server(2255): pocketmine\Server->tick()
12.06 13:00:53 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2507): pocketmine\Server->checkTickUpdates(integer 3109, double 1528830053.9337)
12.06 13:00:53 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2356): pocketmine\level\Level->doTick(integer 3109)
12.06 13:00:53 [Server] Server thread/DEBUG #5 src/pocketmine/level/Level(751): pocketmine\Player->onUpdate(integer 3109)
12.06 13:00:53 [Server] Server thread/DEBUG #4 src/pocketmine/Player(1702): pocketmine\Player->processMovement(integer 1)
12.06 13:00:53 [Server] Server thread/DEBUG #3 src/pocketmine/Player(1595): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:53 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(701): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:53 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(aliuly\mtp\Main object, pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:53 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): aliuly\mtp\Main->onMove(pocketmine\event\player\PlayerMoveEvent object)
12.06 13:00:53 [Server] Server thread/CRITICAL Error: "Call to undefined method aliuly\mtp\Main::getScheduler()" (EXCEPTION) in "MagicTelePortal_dev-11.phar/src/aliuly/mtp/Main" at line 245
12.06 13:00:53 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'MagicTelePortal v1.3.2-6': Call to undefined method aliuly\mtp\Main::getScheduler() on aliuly\mtp\Main
12.06 13:00:51 [Server] Server thread/DEBUG #12 /jar/pocketmine/pmmp/1.4.0-alpha12/PocketMine-MP.phar(9): include(string phar:///jar/pocketmine/pmmp/1.4.0-alpha12/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PORTALS DO NOT TP YOU

**Comment by SOF3** [comment]
Don't use development builds.
